### PR TITLE
SpreadsheetApp externs added

### PR DESCRIPTION
**Pull request by vladimirvelikov**

### CODE REVIEW

**Comment by tong** [comment]
Thanks!

**Comment by vladimirvelikov** [comment]
Thank you for the ones you had already! I'm planning to add some more in
the next days - hopefully all of the remaining ones.

**Comment by tong** [comment]
Kewl! Also let me also know if and for what you are using it if you want.

**Comment by vladimirvelikov** [comment]
Co-running a food coop and managing orders in google sheets. Doing lots of
automation with apps script on top of a simple spreadsheet (order tracking,
email notifications, cart caluclation, delivery route optimization). Don't
ask me why I do it in sheets :) as nobody understood my reasons so far. The
main one is that it is very easy to handover to a nonprogrammer and they
could just continue without the fancy automation.
Anyway. Used to write painful JS inside the apps script editor, despite
being a Haxe fan for quite a while now. What turned things around is that
the company I work for switched to Haxe from AS and JS and coidng in pure
JS became more and more painful since. Just the other day I discovered
node-google-apps-script, which syncs almost seamlessly between the local
filesystem and google drive, so I now code in FlashDevelop/HaxeDevelop and
then changes are auto-uploaded to GDrive, then I just need to refresh the
apps script editor and run a quick test to verify all's fine. Everything's
at least 10 times faster this way. Haxe for the win.

**Comment by bablukid** [comment]
Thx for the nice work !
@vladimirvelikov for your information, I'm working on a food coop software, made in haxe, open-source.
Only in french currently, sorry !
http://www.cagette.net/
https://github.com/bablukid/cagette

**Comment by tong** [comment]
Why are you posting this ? It has nothing to do with google-apps-scripts, has it ?

**Comment by bablukid** [comment]
nope sorry, didnt find another way to talk to vladimir. you can delete it, no problem

**Pull request merged**
