### PR TITLE
Fixes to SpreadsheetApp and MimeType

### PR DESCRIPTION
**Pull request by vladimirvelikov**
MimeTypes can be accessed in a similar fashion to the AppsScript syntax;
some other fixes;

### CODE REVIEW

**Review by tong — COMMENTED** [review]
The static fields should be of type String not MimeType. Also what would be the benefit of this change? If we want strict check we could remove `from String` from the abstract.

**Comment by vladimirvelikov** [comment]
The way I suggest it, it gets compiled to the same thing you would write in plain AppsScript Instead of a string.

Sou you have 
`filesIterator.getFilesByType(MimeType.GOOGLE_SHEETS);`
instead of
`filesIterator.getFilesByType("GOOGLE_SHEETS");`

The former has the benefit of being a little better to search for and more self-explaining to a newcomer. Plus if the string behind the constant in Apps Script ever changes (very unlikely I know), you're on the safe side.

The types are MimeType because that's how the methods expecting such a parameter are typed in the DriveApp.hx externs. Provides nice type safety.

**Comment by tong** [comment]
That's incorrect.
The methods in DriveApp expect a String, the type MimeType doesn't exist at all (only as abstract string in haxe), compiler would complain.

**Comment by vladimirvelikov** [comment]
I was referring to the extern definition https://github.com/tong/google-apps-script/blob/dev/src/google/apps/script/DriveApp.hx

If you look at the getFilesByType() method, it requires a MimeType parameter.

**Comment by tong** [comment]
Yes, but MimeType is a String.

**Comment by vladimirvelikov** [comment]
I guess it's a matter of preference, what you want in the compiled code. To
me MimeType.GOOGLE_SHEETS is better than "GOOGLE_SHEETS". It would get
compiled like the former with my suggestion. If you prefer the latter -
fair enough.

P. S. Also not sure, you're getting code completion the way it is now. I
suspect this is what drove me to change it, but not sure. Anyway, thanks
for taking the time to discuss it.

**Comment by tong** [comment]
I am not sure about code completion, anyhow your code doesn't compile, try it.

**Comment by vladimirvelikov** [comment]
Using it in production actually. Will check thoroughly in the evening.
Maybe something's missing in the commit, or it is because I'm compiling
with -D js-classic?

**Comment by tong** [comment]
`-D js-classic` gets added by default when using the haxelib.

`google.apps.script.DriveApp.getFilesByType(google.apps.script.MimeType.GOOGLE_APPS_SCRIPT);` :

```
Hello.hx:5: characters 51-97 : google.apps.script.MimeType should be String
Hello.hx:5: characters 51-97 : For function argument 'mimeType'
```

**Comment by vladimirvelikov** [comment]
Just gave it a try. Indeed in the version on haxelib DriveApp.getFilesByType expects a string, whereas here on GitHub it is MimeType. I was working with the GitHub version and it must have been giving me compile errors, that's probably why I've looked into it and changed it. If I'm not missing something, you might want want to change it to string here too.

**Pull request closed without merging**
